name: Build nightly

on:
  push:
    branches: ["master"]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: ["master"]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          make
      - name: Prepare for build publishing
        run: |
          mkdir -p ~/artifacts
          cp dsx_firmware.nds ~/artifacts
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v3
        with:
          path: ~/artifacts/*
          name: build
